filter:
  excluded_paths:
    - 'tests/'
  dependency_paths:
    - 'tools/'
    - 'vendor/'

build:
  image: default-bionic
  dependencies:
    override:
      - composer update --no-interaction --prefer-dist
  nodes:
    analysis: # see https://scrutinizer-ci.com/docs/tools/php/php-scrutinizer/ 
      project_setup: {override: true}
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
          - command: vendor/bin/phpunit --testdox --coverage-clover=coverage.clover
            coverage:
              file: coverage.clover
              format: clover
